//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recent Folder.
        /// </summary>
        public static string Add_Recent_Folder {
            get {
                return ResourceManager.GetString("Add_Recent_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_Down_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Down_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_Up_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Up_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Continue to synchronize and save?.
        /// </summary>
        public static string ConfirmSync {
            get {
                return ResourceManager.GetString("ConfirmSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronise library file.
        /// </summary>
        public static string ConfirmSyncCaption {
            get {
                return ResourceManager.GetString("ConfirmSyncCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Expand_32 {
            get {
                object obj = ResourceManager.GetObject("Expand_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; no longer exists. Remove from menu?.
        /// </summary>
        public static string Folder___0___no_longer_exists__Remove_from_menu_ {
            get {
                return ResourceManager.GetString("Folder___0___no_longer_exists__Remove_from_menu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_Open_16xLG {
            get {
                object obj = ResourceManager.GetObject("folder_Open_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Add {
            get {
                object obj = ResourceManager.GetObject("Op_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_And {
            get {
                object obj = ResourceManager.GetObject("Op_And", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Concatenate {
            get {
                object obj = ResourceManager.GetObject("Op_Concatenate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Conditional {
            get {
                object obj = ResourceManager.GetObject("Op_Conditional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Divide {
            get {
                object obj = ResourceManager.GetObject("Op_Divide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_EqualTo {
            get {
                object obj = ResourceManager.GetObject("Op_EqualTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_GreaterThan {
            get {
                object obj = ResourceManager.GetObject("Op_GreaterThan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_LessThan {
            get {
                object obj = ResourceManager.GetObject("Op_LessThan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Multiply {
            get {
                object obj = ResourceManager.GetObject("Op_Multiply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Not {
            get {
                object obj = ResourceManager.GetObject("Op_Not", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_NotEqualTo {
            get {
                object obj = ResourceManager.GetObject("Op_NotEqualTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_NotGreaterThan {
            get {
                object obj = ResourceManager.GetObject("Op_NotGreaterThan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_NotLessThan {
            get {
                object obj = ResourceManager.GetObject("Op_NotLessThan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Or {
            get {
                object obj = ResourceManager.GetObject("Op_Or", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Subtract {
            get {
                object obj = ResourceManager.GetObject("Op_Subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Op_Xor {
            get {
                object obj = ResourceManager.GetObject("Op_Xor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Open_6296 {
            get {
                object obj = ResourceManager.GetObject("Open_6296", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_16xLG {
            get {
                object obj = ResourceManager.GetObject("refresh_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string Save_file {
            get {
                return ResourceManager.GetString("Save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to open.
        /// </summary>
        public static string Select_the_file_to_open {
            get {
                return ResourceManager.GetString("Select_the_file_to_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the media file(s) to add.
        /// </summary>
        public static string Select_the_media_file_s__to_add {
            get {
                return ResourceManager.GetString("Select_the_media_file_s__to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the media folder to add.
        /// </summary>
        public static string Select_the_media_folder_to_add {
            get {
                return ResourceManager.GetString("Select_the_media_folder_to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Views_7953_32 {
            get {
                object obj = ResourceManager.GetObject("Views_7953_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0:n0} new work(s) will be added to the library file.
        ///.
        /// </summary>
        public static string WorksAdded {
            get {
                return ResourceManager.GetString("WorksAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may synchronise the library file with the ID3 work data in your media prior to saving. If you choose to do this, the following {0:n0} operation(s) will be performed:
        ///
        ///.
        /// </summary>
        public static string WorksChanged {
            get {
                return ResourceManager.GetString("WorksChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The previously loaded ID3 tag data of {0:n0} missing work(s) will be removed from the library file.
        ///.
        /// </summary>
        public static string WorksDeleted {
            get {
                return ResourceManager.GetString("WorksDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The embedded ID3 tag data of {0:n0} work(s) will be overwritten to match the current contents of the library file.
        ///.
        /// </summary>
        public static string WorksPending {
            get {
                return ResourceManager.GetString("WorksPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The contents of the library file will be updated to match the currently embedded ID3 tag data of {0:n0} work(s).
        ///.
        /// </summary>
        public static string WorksUpdated {
            get {
                return ResourceManager.GetString("WorksUpdated", resourceCulture);
            }
        }
    }
}
