namespace TagScanner.Terms
{
    public enum Fn
    {
        Compare,
        Concat, Concat_2, Concat_3, Concat_4,
        Contains, ContainsX,
        Count, CountX,
        Empty,
        EndsWith, EndsWithX,
        Equals, EqualsX,
        Format,
        IfThenElse,
        IndexOf, IndexOfX,
        Input,
        Insert,
        Join,
        LastIndexOf, LastIndexOfX,
        Length,
        Lower,
        Max,
        Min,
        Pow,
        Print, PrintLine,
        Remove,
        Replace, ReplaceX,
        Round,
        Sign,
        StartsWith, StartsWithX,
        Substring,
        ToString,
        Trim,
        Truncate,
        Upper,
    }
}
